### ISSUE TITLE
How to set some semantic labels to void

### ISSUE THREAD

**Issue by jmwang0117** [Harry-Zhi/semantic_nerf#12]
Thank you for your awesome work！！！

I plan to set the semantics of some instances to void when training the model, because I don't want some instances to be segmented, what can I do?

thanks！！！

**Comment by Harry-Zhi** [comment]
Hi @jmwang0117,

As far as I can well, the most straightforward way could be setting the instances that you did not want to predict as label 0 (void class), so they will not be penalised during training. Though at inference time, you will still predict some results on these regions and you could simply mask them out for visualisation purposes. See issue #3 .
