### ISSUE TITLE
config/models for Scannet 

### ISSUE THREAD

**Issue by MisEty** [Harry-Zhi/semantic_nerf#14]
Hello!
Can you provide more files(configs of parameters setting, pretrained models...) on Scannet dataset in the paper?
Thanks

**Comment by Harry-Zhi** [comment]
Hi @MisEty,

I have uploaded the config file for ScanNet in the repo now, which has the same hyper-parameters to replica.

As to pre-trained models, I will have a look and upload once I went back to lab. Will keep you posted.
