### ISSUE TITLE
meaning of pixel-wise denoising

### ISSUE THREAD

**Issue by addy1997** [Harry-Zhi/semantic_nerf#15]
HI @Harry-Zhi,

Firstly, this is amazing work. I had a query, what do you mean by pixel-wise denoising? Is it similar to image deblurring?

**Comment by Harry-Zhi** [comment]
HI @addy1997,

In case it is still useful, the pixel-wise denoising means recover the randomly perturbed pixels of trainging labels by training Semantic-NeRF model and re-rendering new labels at the same camera poses. As a result, we could obtain de-noised labels out of noisy training labels. It is somewhat related to the denoising tasks (e.g., peper noises) from the natural images using some smoothing techinique.
