### ISSUE TITLE
KeyError when training on ScanNet

### ISSUE THREAD

**Issue by HLinChen** [Harry-Zhi/semantic_nerf#17]
The error is that lacking sample_step:

Experiment GPU is 0.
INFO - 2022-08-30 21:44:12,892 - trainer - Using gpu's: 0
----- ScanNet Dataset with NYUv2-40 Conventions-----
processing ScanNet scene:  scene0010_00
Traceback (most recent call last):
  File "train_SSR_main.py", line 224, in <module>
    train()
  File "train_SSR_main.py", line 168, in train
    sample_step=config["experiment"]["sample_step"],
KeyError: 'sample_step'

**Comment by Harry-Zhi** [comment]
Hi @HLinChen ,

Thanks for spotting this. I have added the missing keywords and re-run the exp again. The training on ScanNet should be fine now.
