### ISSUE TITLE
Generate per scene semantic img

### ISSUE THREAD

**Issue by mtk380** [Harry-Zhi/semantic_nerf#18]
The code is wonderful. But I have some trouble generating per scene semantic img from this code. 
`o3d_mesh_canonical_clean.vertex_colors = o3d.utility.Vector3dVector(v_colors/255.0)`
Could you please give me some advice?

**Comment by Harry-Zhi** [comment]
Hi @mtk380,

Could you let me know what are the detailed problems you met during mesh extraction?  So I could discuss with you and fix possible issues in my codebase if any.

**Comment by Harry-Zhi** [comment]
Close it for now. Feel free to re-open it if you have any further questions.
