### ISSUE TITLE
Indexing error when generating rays

### ISSUE THREAD

**Issue by yzheng97** [Harry-Zhi/semantic_nerf#2]
Thanks for the graceful codebase. When switching the depth type from z-dim to euclidean, the error occurs due to this line: 
https://github.com/Harry-Zhi/semantic_nerf/blob/bb98f10b6d5faf334e788b0ce1461a961ec5c17f/SSR/models/rays.py#L57

The proper way might be
`dirs = dirs * (1. / norm)`
`dirs = dirs[:, :, :, None]`

**Comment by Harry-Zhi** [comment]
Hi @yzheng97,

Many thanks for your feedback.

You are right, we can either remove [:, :, :, None]  in your mentioned line or turn the keep_dim flag to false during norm generation.

I have made a quick fix and the dimension error should be gone.

Best,
Shuaifeng
