### ISSUE TITLE
 pre-rendered Replica data can't download

### ISSUE THREAD

**Issue by anghaocheng** [Harry-Zhi/semantic_nerf#21]
Thank you very much for your work and sharing
However, when I download the pre-rendered Replica data, it shows failure at the end of the download. 
Is there any other way to download it?

**Comment by Harry-Zhi** [comment]
@anghaocheng Hi,
Is the data downloading still fails?  If so, I can make a copy on BaiduYun so that you could try to get dataset.

Please let me know if the dataset is okay or not.

**Comment by wqx854987945** [comment]
> 

Hi, can not download this data neither. Please make a copy on BaiduYun. Finally, thank you  for your excellent work.

**Comment by wqx854987945** [comment]
I succeed. Maybe you can print on your terminal " wget http://www.dropbox.com/sh/9yu1elddll00sdl/AAC-rSJdLX0C6HhKXGKMOIija?dl=0 --no-check-certificate ".Then it will automatically skip to "https://uc7519722b0c946c2344253902e7.dl.dropboxusercontent.com/zip_download_get/BUUi6T24ZY0KLXdtrjv4g_CRmkUN7Bn_hn0CuybsoXBFGRKU42llwhngG2lmc1u_SXC0Q7JxrrN5X9ZA3vkLG_L6Uy6qiyWFi7T6NRp96zymgA"

**Comment by anghaocheng** [comment]
Thanks for your reply! I finally downloaded and unzipped the dataset successfully. The dataset is OK

**Comment by anghaocheng** [comment]
That 's OK. Thank you very much
&nbsp;


1550113071
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月18日(星期五) 上午10:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Harry-Zhi/semantic_nerf]  pre-rendered Replica data can&#39;t download (Issue #21)





 
I succeed. Maybe you can print on your terminal " wget http://www.dropbox.com/sh/9yu1elddll00sdl/AAC-rSJdLX0C6HhKXGKMOIija?dl=0 --no-check-certificate ".Then it will automatically skip to "https://uc7519722b0c946c2344253902e7.dl.dropboxusercontent.com/zip_download_get/BUUi6T24ZY0KLXdtrjv4g_CRmkUN7Bn_hn0CuybsoXBFGRKU42llwhngG2lmc1u_SXC0Q7JxrrN5X9ZA3vkLG_L6Uy6qiyWFi7T6NRp96zymgA"

**Comment by Harry-Zhi** [comment]
> 

I have added the BaiduYun link for replica dataset. Please check the readme of the git repo.

**Comment by Harry-Zhi** [comment]
Close it for now. Feel free to re-open it if you have any further questions.
