### ISSUE TITLE
Question of randomly generated camera poses in Replica

### ISSUE THREAD

**Issue by HLinChen** [Harry-Zhi/semantic_nerf#25]
Hi,

Thank you for the wonderful work. You said camera poses of Replica are randomly generated in #5 . However, the images rendered seem to be in a smooth trajectory instead of produced from random camera poses. May I ask what is the algorithm used to generate the trajectory?

Thanks!

**Comment by Harry-Zhi** [comment]
@HLinChen 
Hi,
The main pipeline of generating random trajctories are as follows:
1. Randomly sample a set of camera positions and camera look-at points within the scene
2. We can interpolate a serious of smooth camera positions and look-at points between using for example spline interpolation.
3. For each pair of camera look-at point and camera position, we could generate a camera pose matrix.

There is also a similar public implementation from MoreFusion repo from our group  and hope it is useful to you. 
Please check [here](https://github.com/wkentaro/morefusion/blob/0381b6a8d89442697e8b4fb8c29f81177a0d25be/morefusion/geometry/look_at.py#L13) and [here](https://github.com/wkentaro/morefusion/blob/0381b6a8d89442697e8b4fb8c29f81177a0d25be/morefusion/simulation/scene_generation/base.py#L352)

**Comment by HLinChen** [comment]
Thanks for your help!
