### ISSUE TITLE
A question about coloured mesh

### ISSUE THREAD

**Issue by aobannong** [Harry-Zhi/semantic_nerf#26]
Hello, thanks for your excellent job! Generating a semantic model in a nerf-way is so cool. With the shared codes, I succeeded in training with Replica data and stopped the training when the testing results are perceptually good. However, when generating colored meshes, I met some trouble because no "mesh.ply" file can be found. I wonder where I can get the "mesh.ply" file.

**Comment by RobinsonKO** [comment]
Hi bro,have you found "mesh.ply"?

**Comment by RobinsonKO** [comment]
> Hi bro,have you found "mesh.ply"?

Need to download whole dataset.

**Comment by Harry-Zhi** [comment]
@RobinsonKO @aobannong  Hi, sorry for the late reply.

As you have solved, the mesh.ply comes from original datasets which are mainly used to find appropriate 3D volumes to infer networks and align coordinates with original mesh for the ease of following evaluation if necessary.

**Comment by Harry-Zhi** [comment]
@RobinsonKO  Hi, sorry for the late reply.

As you have solved, the mesh.ply comes from original datasets which are mainly used to find appropriate 3D volumes to infer networks and align coordinates with original mesh for the ease of following evaluation if necessary.

**Comment by wave-transmitter** [comment]
Hi,

first of all congrats for the amazing work! Assuming that the mesh.ply is not available, e.g. train the model on custom data, is there a shortcut to create a mesh-like file from the data?

**Comment by Harry-Zhi** [comment]
> Hi,
> 
> first of all congrats for the amazing work! Assuming that the mesh.ply is not available, e.g. train the model on custom data, is there a shortcut to create a mesh-like file from the output (or input) data?

Hi, probably there could be other better ways from recent related works and I may not be aware of all of them.

As far as I can tell, usually it is good to have some prior knowledge of how the learned space spans within the 3D world, either from a 3D model or get a roungh 3D axis-aligned bounding box of underlying scenes using, for example,  re-projected 3D point clouds from depth maps or SfMs from sequence of colour images (like what ManhattanSDF,  NeuS, NeuRIS did).

Or, if you have no such information, currently I guess the best we can do is something like the original NeRF repo, as the underlying blender object lies within a bounded and unknown volume, we could find where the reconstructed scene is by 	trial and error.
