### ISSUE TITLE
About camera poses

### ISSUE THREAD

**Issue by donjiaking** [Harry-Zhi/semantic_nerf#28]
Hi, I wonder what is the camera format in `traj_w_c.txt` ? Does the filename "*_w_c" suggests it is in world to camera format? Thank you very much.

**Comment by Harry-Zhi** [comment]
Hi @donjiaking ,

The camera pose are 'camera to world' transformations (T_ab means transformation for b to a). Sorry for the confusion.

Please note that the camera coordinates follow OpenCV convention where x,y,z axes are 'right', 'down', 'forward'.
