### ISSUE TITLE
Correlation bwteen traj_w_c.txt and transform.json from nerfstudio

### ISSUE THREAD

**Issue by vrahnos3** [Harry-Zhi/semantic_nerf#31]
Hello, thanks for the great work, 
I am processing Replica dataset with nerfstudio and I am trying to correlate your traj_w_c.txt with nerfstudio's transform.json but it doesn't make sense. I tried even to maintain camera coordinate system to OpenCv but I didnt find similarities between the two files. Is there any way to produce your traj_w_c.txt with nerfstudio? 
Thank you!

**Comment by Harry-Zhi** [comment]
Hi @vrahnos3 ,
thanks for your interests in our work.
I am a bit sorry that I have not investigated nerfstudio json file too much.

The provided Replica data has traj_w_c.txt, containing typical camera to world transformations (i.e., T_wc) with opencv camera and typical world coordinate ( z-axis is opposite to gravity). 
During data preparation, I use habitat-sim to render multi-modal images of scenes.  I guess one thing to note is that Replcia and habitat-sim have different convention w.r.t. to world coordinates ( gravity) and cameras: see https://github.com/facebookresearch/Replica-Dataset/issues/29 and https://github.com/facebookresearch/Replica-Dataset/issues/37.

Therefore, if you use habitat-sim to render with my given poses, if need to rotate my provided T_wc to match the conventions.
If you use the provided pose to training, I guess it should just work well. Original NeRF repo follows OpenGL camera convention so there will be difference in ray generation to this repo: https://github.com/Harry-Zhi/semantic_nerf/blob/45b0277236de7f6585bfd7f80ac6789930fd08b8/SSR/models/rays.py#L42.

Hope this helps.

**Comment by VladimirYugay** [comment]
@Harry-Zhi are the poses you fed to the habitat somehow preprocessed?

I tried to put the agent (default settings) in the pose taken from `traj_w_c.txt` for `room_0` in Replica, but the rendered image doesn't match yours. So how exactly can I modify the pose in order to have the same rendering as you? 

The code I use to pose the agent:

```
import quaternion as qt


poses = np.loadtxt("Semantic-Nerf-Replica/room_0/Sequence_1/traj_w_c.txt", delimiter=" ").reshape(-1, 4, 4)
pose = poses[0]

R = qt.from_rotation_matrix(pose[:3, :3])
t = pose[:3, 3]

agent = self._sim.agents[self._sim_settings["default_agent"]]
agent_state = habitat_sim.AgentState()
agent_state.position = t
agent_state.rotation = R
agent.set_state(agent_state)
observations = self._sim.get_sensor_observations()

```

**Comment by VladimirYugay** [comment]
Hi @Harry-Zhi, thanks for your response. 

So these are the OpenCV and OpenGL coordinate systems:
![image](https://user-images.githubusercontent.com/12258972/236419702-b6c77e88-8ce9-4cb8-a67f-d295f387207b.png)

For OpenCV: X goes right, Y goes down, Z goes forward
For OpenGL: X goes Right, Y goes up, Z goes backward

Now, I'm trying to put the robot in Habitat+Replica `habitat_pose` given the pose provided by your `pose`. Both of them are 4x4 matrices.

You also mentioned:

1. While you follow the OpenCV convention for your case `z-axis up`, while on the picture above `y-axis down`
    That means, that in order to get a pure OpenCV format, we need to swap Y and Z and negate Z
    
    ```
     X, Y, Z = pose[0, :], pose[1, :], pose[2, :]
     opencv_pose = np.array([X, -Z, Y, [0, 0, 0, 1]])
    ```

    
    
2. Now after we converted your pose format to the OpenCV format, we go to the OpenGL (Habitat) pose:
    ```
     X, Y, Z = opencv_pose[0, :], opencv_pose[1, :], opencv_pose[2, :]
     opengl_pose = np.array([X, -Y, -Z, [0, 0, 0, 1]])
    ```

After doing this, I still don't get the rendering similar to yours. Am I missing something?

**Comment by Harry-Zhi** [comment]
@VladimirYugay We have provided data generation codes for Replica in the latest commit. You could check it [here](https://github.com/Harry-Zhi/semantic_nerf/tree/main/SSR/data_generation). You could feed your poses and get rendered images.

Please let me know if you have further issues.

**Comment by gtangg12** [comment]
I think the issue lies here (which is used for both data generation + dataset loading for NeRF):
```
def opencv_to_opengl_camera(transform=None):
    if transform is None:
        transform = np.eye(4)
    return transform @ trimesh.transformations.rotation_matrix(
        np.deg2rad(180), [1, 0, 0]
    )
```
I don't think this is a correct change of basis for the camera2world transform, should be smth like X@Pose@X^T where X is diagonal matrix that converts between OpenCV and OpenGl coord conventions. I think currently to convert you can just multiply the second and third rows by -1 to get nerfstudio OpenGl cam2world coord convention.
