### ISSUE TITLE
Instance Labels in pre-rendered dataset Replica Dataset

### ISSUE THREAD

**Issue by pushkalkatara** [Harry-Zhi/semantic_nerf#37]
Hi, Thanks for the amazing work!

I downloaded the pre-rendered Replica dataset from provided link but was unable to find the instance label folder for each scene.
The directory `semantic_instance` is missing from each scene. In the dataset this is optionally loaded [here](https://github.com/Harry-Zhi/semantic_nerf/blob/main/SSR/datasets/replica/replica_datasets.py#L17).

it would be great if the link can be updated with the instance id folders as well.

Alternatively, if the data rendering scripts from Habitat can be open-sourced that would be really great.

Thanks!

**Comment by Harry-Zhi** [comment]
@pushkalkatara Hi, I have pushed the instance segmentation masks of Sequence 1 as well as their colorizations in the shared dropbox folder (a newly added zip file). Please have a check!

As to the generation codes, I am sorry they are not public available but I am happy to try to render some for you if poses can be provided.

**Comment by pushkalkatara** [comment]
Thanks @Harry-Zhi for sharing! I just needed renders from these poses.
