### ISSUE TITLE
Implementation of semantic_nerf for Outdoor scenes

### ISSUE THREAD

**Issue by engrkhurramshabbir** [Harry-Zhi/semantic_nerf#38]
Hi,

Thanks for sharing your work.

Code works fine for the indoor scenes. I trying to implement this code on images of an outdoor seen e.g. building. But I am unable to generate the render scenes. I will be glad if you can guide me about parameters I need to change to get the required output for outdoor scenes.

**Comment by Harry-Zhi** [comment]
Hi. Sorry for the late reply.

The currents codes works good for bounded indoor scenes as we simply scale all the 3D positions by a factor of 10 https://github.com/Harry-Zhi/semantic_nerf/blob/b79f9c3640b62350e9c167a66c273c2121428ce1/SSR/training/trainer.py#L823. I think the key differences lies on how to handle  the relationship between camera poses and scene volume.

Several methods (like NeUS, VolSDF, etc) have proposed to take better camera poses by re-normalizing all camera poses to a unit sphere. 

If you want to apply semantic-nerf to unbounded outdoor scenes, I think applying NeRF++ setup could be a reasonable way where two separate Sem-NeRFs are trained to take care of foreground and background areas. For each region, you could apply a proper camera normalization process to learn the content within/outside a "sphere". Other methods like UrbanNeRF could also be taken a backend.

If you want to learn a bounded  or only a local region corner of somewhere outside, I think it should work similarly with indoor bounded areas.

**Comment by engrkhurramshabbir** [comment]
Hi, I am able to implement semantic nerf on the outdoor unbounded scene. But now I am facing problem with mesh reconstruction (snapshot attached). I will be to have suggestions/guidance regarding it.
![Screenshot 2023-12-26 193640](https://github.com/Harry-Zhi/semantic_nerf/assets/95455487/7367bc5d-d6bc-4cfd-9f24-c28f4477df16)
