### ISSUE TITLE
Generating the traj_w_c file for custom dataset

### ISSUE THREAD

**Issue by AadeshVarude** [Harry-Zhi/semantic_nerf#40]
Thank you for your great contribution and for sharing this wonderful code.

I am trying to run the semantic nerf on my custom dataset where I have a bunch of images on which I wish to train this network. How do I generate the traj_w_c file as well as other required files?

Thank you in advance for your help.

**Comment by Harry-Zhi** [comment]
Hi. We have updated the data generation codes in the repo. The traj_w_c is camera to world camera poses under OpenCV convention. The codes will transform it properly to OpenGL-camera to Habitat-World-coordinate.


As to generate this  traj_w_c, a straightforward way is to randomly sample N camera positions and N look-at points (which corresponds to N discrete camera poses) before smoothly interpolating spatially to, for example, 5*N or 10*N poses.
