### ISSUE TITLE
如何获取habitat-sim的相机内参

### ISSUE THREAD

**Issue by zhuisa** [Harry-Zhi/semantic_nerf#41]
您好！在data_generation文件夹中使用habitat-sim生成数据集时，相机内参是多少呢？或者说如何获取相机内存呢？感谢您的答复。

**Comment by Harry-Zhi** [comment]
Hi. The adopted camera for Replica is a perfect pin-hole camera. 
You can see how we set Replica intrinsic here (fov and image resolution are two key parameters required to determine Replica camera intrinsic)
: https://github.com/Harry-Zhi/semantic_nerf/blob/b79f9c3640b62350e9c167a66c273c2121428ce1/SSR/training/trainer.py#L55.

It correlates to data generation config here: https://github.com/Harry-Zhi/semantic_nerf/blob/b79f9c3640b62350e9c167a66c273c2121428ce1/SSR/data_generation/settings.py#L8C9-L8C9, where you can specify fov and image size.

**Comment by zhuisa** [comment]
感谢！
