### ISSUE TITLE
Training time for a scene 

### ISSUE THREAD

**Issue by WenM1222** [Harry-Zhi/semantic_nerf#42]
I noticed in your paper that the model was trained for 200,000 iterations on a single RTX2080Ti GPU. Could you please provide an estimate of the time it took to complete this training?

**Comment by Harry-Zhi** [comment]
Hi. If no rendering for training and test images are required, it takes approximately 9-10 hours at most in my case. If you conduct rendering for visualization during training every 20k/50k steps, it may increases to 11-12 hours.
