### ISSUE TITLE
What format is the "traj_w_c.txt" file in the pre-rendered replica dataset in?

### ISSUE THREAD

**Issue by kurtjcu** [Harry-Zhi/semantic_nerf#6]
Hi,
Thanks for sharing your code, I am looking to explore this system with other datasets and would like to know thew format of the "traj_w_c.txt" in the pre-rendered replica dataset(s).

Cheers,
Kurt

**Comment by Harry-Zhi** [comment]
Hi

Sorry for the late reply.

The camera poses are stored as 4x4 transformation matrix in homogenous-coordinate:
https://github.com/Harry-Zhi/semantic_nerf/blob/fcdd3c69550be5de60a4cc55be13f5f296ab82f9/SSR/datasets/replica/replica_datasets.py#L30

The camera coordinate follows the typical opencv-convention x-right,y-down, z-forward) and the world coordinate is z-up. This is not the same to that of original NeRF repo where camera follows OpenGL convention.

Hope this helps!
