### ISSUE TITLE
info_semantic.json for replica

### ISSUE THREAD

**Issue by DarlingHang** [Harry-Zhi/semantic_nerf#7]
Can you share a copy of info_semantic.json so we can directly use prerendered replica data instead of having to download the whole dataset?

**Comment by Harry-Zhi** [comment]
Hi,

Thanks for the good suggestions.

 I will check the liscense of Replica and will add this to the dataset soon if allowed.

**Comment by Harry-Zhi** [comment]
Hi. FYI, the json file have been put into a separate folder called semantic_json.zip in https://www.dropbox.com/home/Public_Hosting/Semantic_NeRF(ICCV2021)/Replica_Dataset.
