### ISSUE TITLE
Is there rendering code or trajectory-generation code?

### ISSUE THREAD

**Issue by soskek** [Harry-Zhi/semantic_nerf#8]
For Replica and/or scannet.
It would be very helpful.

**Comment by Harry-Zhi** [comment]
Hi,

I am sorry that the rendering codes are not available yet but for rendering Replica scenes, the pipeline is straightforward.
You could probablu have a look at habitat-sim which works with quite well with Replica for rendering purposes. If you have further questions, I am quite happy to discuss.

For ScanNet, I simply used the raw scans from original dataset and did not modify the data.

Hope this helps.

**Comment by soskek** [comment]
Thank you for your fast reply! I see. I'll have a look at it first!
